options:
  credentials:
    description: |
      The base64-encoded contents of a JSON file containing vSphere credentials.

      The credentials must contain the following keys: vsphere_ip, user,
      password, datacenter, and datastore.

      This can be used from bundles with 'include-base64://' (see
      https://docs.jujucharms.com/2.4/en/charms-bundles#setting-charm-configuration-options-in-a-bundle),
      or from the command-line with 'juju config vsphere credentials="$(base64 /path/to/file)"'.

      It is strongly recommended that you use 'juju trust' instead, if available.
    type: string
    default: ""
  vsphere_ip:
    description: IP address of the vSphere server.
    type: string
    default: ""
  user:
    description: Username of a valid vSphere user.
    type: string
    default: ""
  password:
    description: Password of a valid vSphere user.
    type: string
    default: ""
  datacenter:
    description: |
      vSphere datacenter name. In the vCenter control panel, this can be found
      at Inventory Lists > Resources > Datacenters.
    type: string
    default: ""
  datastore:
    description: |
      Datastore to use for provisioning volumes using storage classes and
      persistent volume claims. Defaults to 'datastore1'.
    type: string
    default: "datastore1"
  folder:
    description: |
      Virtual center VM folder path under the datacenter. Defaults to 'juju-kubernetes'.
      This value must not be empty.
    type: string
    default: "juju-kubernetes"
  respool_path:
    description: |
      Path to resource pool under the datacenter.
    type: string
    default: ""
